services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    networks:
      - habitify-net

networks:
  habitify-net: